//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR4_UP.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtraServices
    {
        public int IDServices { get; set; }
        public string Services { get; set; }
        public string DescriptionServices { get; set; }
        public decimal PriceServices { get; set; }
    }
}
