//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR4_UP.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guests
    {
        public int IDGuests { get; set; }
        public string LastNameGuest { get; set; }
        public string NameGuest { get; set; }
        public string MiddleNameGuest { get; set; }
        public string PhoneNumber { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string PlaceOfBirth { get; set; }
        public int PassportSeries { get; set; }
        public int PassportNumber { get; set; }
        public System.DateTime WhenIssued { get; set; }
        public string IssuedbyWhom { get; set; }
        public string Registration { get; set; }
    }
}
