//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR4_UP.ApplicationData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Hotel_UP4Entities : DbContext
    {
        private static Hotel_UP4Entities Context;

        public Hotel_UP4Entities()
            : base("name=Hotel_UP4Entities")
        {
        }

        public static Hotel_UP4Entities GetContext()
        {
            if (Context == null)
                Context = new Hotel_UP4Entities();
            return Context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking> Booking { get; set; }
        public virtual DbSet<ExtraServices> ExtraServices { get; set; }
        public virtual DbSet<Guests> Guests { get; set; }
        public virtual DbSet<Price> Price { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
