//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR4_UP.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int IdPrice { get; set; }
        public int IdNumberOfRooms { get; set; }
        public decimal Price1 { get; set; }
        public string Description { get; set; }
    }
}
